FROM python:3.10

RUN apt-get update && \
	apt-get install -y python3-lxml poppler-utils && \
	pip install pdf-diff

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

EXPOSE 8000

ENTRYPOINT [ "bin/start.sh"]